/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the session family and clear the cookie.
         *
         *     Unauthenticated and idempotent on purpose: a user whose access token has already
         *     expired must still be able to end their session, and a logout that returns 401 leaves
         *     the browser holding a live refresh cookie.
         *
         *     Returns ``None`` rather than a ``Response``: FastAPI merges the injected response's
         *     headers only on that path, and returning one directly would drop the Set-Cookie.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change your own password and sign every *other* session out.
         *
         *     Other sessions keep working for up to one access-token TTL: their refresh tokens are
         *     dead immediately, but an access token already issued is self-contained. Fifteen
         *     minutes is the documented cost of not doing a token lookup on the data plane; if that
         *     is ever unacceptable, the fix is a revocation list, not a shorter TTL.
         */
        post: operations["change_password_api_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange the refresh cookie for a new access token and a new refresh token.
         *
         *     Deliberately unauthenticated: by the time a client calls this, its access token has
         *     expired, which is the only reason it is calling.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gateways */
        get: operations["list_gateways_api_v1_gateways_get"];
        put?: never;
        /** Create Gateway */
        post: operations["create_gateway_api_v1_gateways_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/{gateway_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gateway */
        get: operations["get_gateway_api_v1_gateways__gateway_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Gateway
         * @description Takes its keys and targets with it. Every deployed client stops working, which is
         *     why the UI asks for the slug to be typed.
         */
        delete: operations["delete_gateway_api_v1_gateways__gateway_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Gateway
         * @description Partial. The three config sections are deep-merged, so a form that owns one
         *     section can save without knowing what the others contain.
         *
         *     ``slug`` is refused rather than ignored — it is part of a URL clients have deployed.
         */
        patch: operations["update_gateway_api_v1_gateways__gateway_id__patch"];
        trace?: never;
    };
    "/api/v1/gateways/{gateway_id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Keys
         * @description Not paginated: a gateway holds tens of keys, not thousands, and the screen shows
         *     them all at once. The cap in the service is what keeps that true.
         */
        get: operations["list_keys_api_v1_gateways__gateway_id__keys_get"];
        put?: never;
        /**
         * Create Key
         * @description The only response in this API containing a usable secret, and the only time this
         *     one exists. Only ``sha256(secret)`` is stored, so it cannot be shown again.
         */
        post: operations["create_key_api_v1_gateways__gateway_id__keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/{gateway_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Gateway
         * @description Send a probe completion through the real proxy path.
         *
         *     Returns the assembled prompt as well as the answer, which is the part that makes this
         *     a debugging tool rather than a health check: it shows what the system context became
         *     without waiting for real traffic to appear in the request log.
         */
        post: operations["test_gateway_api_v1_gateways__gateway_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invitations
         * @description No ``accept_url`` here, and there cannot be one: only the hash is stored. Use
         *     resend to mint a fresh link.
         */
        get: operations["list_invitations_api_v1_invitations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Invitation
         * @description Validate a link so the page can render before anyone types a password.
         *
         *     Answers 404 for unknown, expired and already-accepted alike: the token is a bearer
         *     credential, and a caller holding the wrong one learns nothing about which it was.
         */
        get: operations["preview_invitation_api_v1_invitations_accept__token__get"];
        put?: never;
        /**
         * Accept Invitation
         * @description Create the account and sign it in.
         *
         *     Two transactions, not one: the directory creates the user and burns the invitation,
         *     then auth opens a session. If the second half fails the account still exists and the
         *     person can sign in normally, which is a better failure than a consumed invitation and
         *     no account.
         */
        post: operations["accept_invitation_api_v1_invitations_accept__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invitation */
        delete: operations["revoke_invitation_api_v1_invitations__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{invitation_id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Invitation
         * @description Mints a new link and invalidates the previous one.
         */
        post: operations["resend_invitation_api_v1_invitations__invitation_id__resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Key
         * @description Soft. The row survives so the request log keeps a reference that resolves, and the
         *     next request with this key is refused — key lookup is never cached.
         */
        delete: operations["revoke_key_api_v1_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Logs
         * @description The request table: metadata only, newest first, cursor-paginated.
         *
         *     Cursor rather than offset because this list is being written to while it is read —
         *     SPEC §12.2's reason, and the one screen where an offset page would visibly duplicate
         *     and skip rows as traffic arrives.
         */
        get: operations["list_logs_api_v1_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Log
         * @description One request in full, including whatever of the transcript was stored.
         *
         *     No time range: the id is a UUIDv7 and carries the millisecond it was minted, so the
         *     server works out which day's partition to look in. A 404 covers "no such request" and
         *     "another organization's request" alike.
         */
        get: operations["get_log_api_v1_logs__log_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_members__member_id__delete"];
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_api_v1_members__member_id__patch"];
        trace?: never;
    };
    "/api/v1/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Summary
         * @description Totals, percentiles, per-model traffic and the error taxonomy, in one read.
         *
         *     Cached for 30 seconds per organization and query. Everything on the dashboard and the
         *     top of the monitoring screen comes from here, so it is the one query worth caching.
         */
        get: operations["metrics_summary_api_v1_metrics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Timeseries
         * @description Bucketed series. The bucket width is the server's decision, not the client's.
         *
         *     A metric is usually several lines — ``latency`` is p50/p95/p99 plus TTFT and
         *     retrieval — so one call fills one chart rather than one line. ``interval`` is a
         *     request, not an instruction: the response says what was used.
         */
        get: operations["metrics_timeseries_api_v1_metrics_timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description The caller's own models plus the global catalog, newest first.
         *
         *     One endpoint for both tabs: ``?scope=global`` and ``?scope=org`` are a filter over the
         *     same list rather than two shapes, so the client pages them identically and a model
         *     cannot appear in one view and not the other.
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        /** Create Model */
        post: operations["create_model_api_v1_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Draft
         * @description Probe a configuration that has not been saved.
         *
         *     Declared before ``/models/{model_id}`` so ``test`` is not swallowed as an id — FastAPI
         *     matches in declaration order, and ``uuid.UUID`` would reject it with a 422 that reads
         *     like the endpoint is broken.
         */
        post: operations["test_draft_api_v1_models_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_api_v1_models__model_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Model
         * @description 409 with the referencing gateways named if one points at this model.
         */
        delete: operations["delete_model_api_v1_models__model_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Model
         * @description Partial. An omitted ``credential`` keeps the stored one; an explicit ``null``
         *     clears it. There is no way to read it back, so rotation is replacement.
         */
        patch: operations["update_model_api_v1_models__model_id__patch"];
        trace?: never;
    };
    "/api/v1/models/{model_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Model
         * @description Send a one-token completion using the model exactly as stored.
         *
         *     Nothing about the request can be overridden here. A caller who could aim a *stored*
         *     credential at a URL of their choosing would have a reveal endpoint in all but name.
         */
        post: operations["test_model_api_v1_models__model_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Organizations
         * @description Every organization for a platform admin; the caller's own, alone, for anyone else.
         *
         *     Not gated on ``platform:administer``: an org user needs this to render their own
         *     organization, and the scope already reduces the answer to one row. A second endpoint
         *     shape for the same information is how the two drift apart.
         */
        get: operations["list_organizations_api_v1_organizations_get"];
        put?: never;
        /** Create Organization */
        post: operations["create_organization_api_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization_api_v1_organizations__organization_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Organization
         * @description Name, slug and defaults for an org admin; ``status`` for a platform admin only.
         *
         *     Refused rather than ignored: an organization that could suspend itself could also
         *     un-suspend itself, which would make suspension advisory.
         */
        patch: operations["update_organization_api_v1_organizations__organization_id__patch"];
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invitation
         * @description Creates the invitation and returns the link — the only time it exists.
         *
         *     There is no email delivery in v1 (task 04, out of scope), so the admin copies the URL
         *     and sends it however they already talk to the person.
         */
        post: operations["create_invitation_api_v1_organizations__organization_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Members
         * @description Readable by every role. Seeing who your colleagues are is not an admin power;
         *     changing them is, and that lives on the two routes below.
         */
        get: operations["list_members_api_v1_organizations__organization_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/g/{slug}/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Completions
         * @description Forward a chat completion, streaming or not.
         */
        post: operations["chat_completions_g__slug__v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/g/{slug}/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description The virtual models this gateway exposes, in OpenAI list format.
         */
        get: operations["list_models_g__slug__v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyCreateRequest */
        ApiKeyCreateRequest: {
            /** Expires At */
            expires_at?: string | null;
            /** Name */
            name: string;
        };
        /**
         * ApiKeyResponse
         * @description Everything about a key except the one thing that matters, which is gone.
         *
         *     ``prefix`` is the durable display form: it carries no secret, and it is what a
         *     customer compares against the key in their own config when working out which one to
         *     revoke.
         */
        ApiKeyResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /**
             * Gateway Id
             * Format: uuid
             */
            gateway_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** BucketResponse */
        BucketResponse: {
            /** Series */
            series: {
                [key: string]: number;
            };
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /**
         * CredentialStatus
         * @description SPEC §5.4: what a response may say about a stored secret, and no more.
         *
         *     ``hint`` can be ``None`` while ``configured`` is ``True`` — for a row written before
         *     hints were stored, and for a global model being read by someone who does not own it.
         */
        CredentialStatus: {
            /** Configured */
            configured: boolean;
            /** Hint */
            hint?: string | null;
        };
        /** ErrorGroupResponse */
        ErrorGroupResponse: {
            /** Error Code */
            error_code: string;
            /** Requests */
            requests: number;
        };
        /** GatewayCreateRequest */
        GatewayCreateRequest: {
            /** Description */
            description?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Limits */
            limits?: {
                [key: string]: unknown;
            };
            /** Locked Params */
            locked_params?: {
                [key: string]: unknown;
            };
            /** Logging Config */
            logging_config?: {
                [key: string]: unknown;
            };
            /** Memory Config */
            memory_config?: {
                [key: string]: unknown;
            };
            /** Model Id */
            model_id?: string | null;
            /** Name */
            name: string;
            /** Param Overrides */
            param_overrides?: {
                [key: string]: unknown;
            };
            /**
             * Routing Mode
             * @default single
             */
            routing_mode: string;
            /** Slug */
            slug: string;
            /** System Context */
            system_context?: string | null;
        };
        /** GatewayResponse */
        GatewayResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Enabled */
            enabled: boolean;
            /** Endpoint Url */
            endpoint_url: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Count */
            key_count: number;
            limits: components["schemas"]["LimitsConfig"];
            /** Locked Params */
            locked_params: {
                [key: string]: unknown;
            };
            logging_config: components["schemas"]["LoggingConfig"];
            memory_config: components["schemas"]["MemoryConfig"];
            /** Name */
            name: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Param Overrides */
            param_overrides: {
                [key: string]: unknown;
            };
            /** Routing Mode */
            routing_mode: string;
            /** Slug */
            slug: string;
            /** System Context */
            system_context: string | null;
            /** Targets */
            targets: components["schemas"]["TargetSummary"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GatewayTestRequest */
        GatewayTestRequest: {
            /** Message */
            message: string;
        };
        /**
         * GatewayTestResponse
         * @description What the probe saw: the prompt, the answer, and where the time went.
         *
         *     Not an error envelope. "The upstream said 401" is the successful answer to "does this
         *     gateway work", and the UI renders it in red itself.
         */
        GatewayTestResponse: {
            /** Assembled Prompt */
            assembled_prompt: components["schemas"]["PromptMessageResponse"][];
            /** Content */
            content?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Locked Overrides */
            locked_overrides?: string[];
            /** Model Name */
            model_name?: string | null;
            /** Ok */
            ok: boolean;
            /** Total Ms */
            total_ms: number;
            /** Upstream Ms */
            upstream_ms: number;
            /** Upstream Status */
            upstream_status?: number | null;
        };
        /**
         * GatewayUpdateRequest
         * @description Partial. Only fields actually present in the body are applied.
         *
         *     ``model_id: null`` is meaningful and allowed: it detaches the gateway from its model,
         *     which is how you park an endpoint without deleting it.
         */
        GatewayUpdateRequest: {
            /** Description */
            description?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Limits */
            limits?: {
                [key: string]: unknown;
            } | null;
            /** Locked Params */
            locked_params?: {
                [key: string]: unknown;
            } | null;
            /** Logging Config */
            logging_config?: {
                [key: string]: unknown;
            } | null;
            /** Memory Config */
            memory_config?: {
                [key: string]: unknown;
            } | null;
            /** Model Id */
            model_id?: string | null;
            /** Name */
            name?: string | null;
            /** Param Overrides */
            param_overrides?: {
                [key: string]: unknown;
            } | null;
            /** Routing Mode */
            routing_mode?: string | null;
            /** System Context */
            system_context?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvitationAcceptRequest */
        InvitationAcceptRequest: {
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** InvitationCreateRequest */
        InvitationCreateRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Role */
            role: string;
        };
        /**
         * InvitationPreviewResponse
         * @description What an unauthenticated visitor may see about a link they hold.
         *
         *     The organization's *name* is here because the page has to say which organization is
         *     being joined; nothing else about it is, and there is no id.
         */
        InvitationPreviewResponse: {
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Organization Name */
            organization_name: string;
            /** Role */
            role: string;
        };
        /** InvitationResponse */
        InvitationResponse: {
            /** Accepted At */
            accepted_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /**
         * IssuedApiKeyResponse
         * @description The one response in this API with a live secret in it.
         *
         *     Returned by ``POST /gateways/{id}/keys`` and nowhere else, because only the hash is
         *     stored. The client is expected to show it once with a warning and then forget it —
         *     reloading the page cannot bring it back, and that is the property being protected.
         */
        IssuedApiKeyResponse: {
            key: components["schemas"]["ApiKeyResponse"];
            /** Token */
            token: string;
        };
        /**
         * IssuedInvitationResponse
         * @description The one response that carries the link.
         *
         *     Only the hash is stored, so this is the single moment it can be shown; the list
         *     endpoint has no ``accept_url`` field to leak later.
         */
        IssuedInvitationResponse: {
            /** Accept Url */
            accept_url: string;
            invitation: components["schemas"]["InvitationResponse"];
        };
        /**
         * LimitsConfig
         * @description SPEC §11. ``None`` means unlimited, which is the v1 default — task 14 enforces
         *     these, and a limit that quietly existed before anyone set one would be a surprise
         *     outage rather than a policy.
         */
        LimitsConfig: {
            /** Concurrent Requests */
            concurrent_requests?: number | null;
            /** Requests Per Day */
            requests_per_day?: number | null;
            /** Requests Per Minute */
            requests_per_minute?: number | null;
            /** Tokens Per Minute */
            tokens_per_minute?: number | null;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /**
         * LoggingConfig
         * @description SPEC §10.2. Full capture by default — bodies are what make distillation possible
         *     — and every part switchable.
         */
        LoggingConfig: {
            /**
             * Enable Distillation
             * @default true
             */
            enable_distillation: boolean;
            /**
             * Log Assembled Prompt
             * @default true
             */
            log_assembled_prompt: boolean;
            /**
             * Log Metadata
             * @default true
             */
            log_metadata: boolean;
            /**
             * Log Request Body
             * @default true
             */
            log_request_body: boolean;
            /**
             * Log Response Body
             * @default true
             */
            log_response_body: boolean;
            /**
             * Metadata Retention Days
             * @default 365
             */
            metadata_retention_days: number;
            /** Redaction Patterns */
            redaction_patterns?: string[];
            /**
             * Retention Days
             * @default 30
             */
            retention_days: number;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember
             * @default false
             */
            remember: boolean;
        };
        /** MemberResponse */
        MemberResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Login At */
            last_login_at?: string | null;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** MemberUpdateRequest */
        MemberUpdateRequest: {
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * MemoryConfig
         * @description SPEC §6.3. Task 10 makes these do something; the shape is settled now.
         *
         *     ``connector_ids`` is empty by default, which means no document memory — a gateway
         *     that silently started reading every connector in the organization would be a
         *     disclosure bug, so the safe default is "nothing".
         */
        MemoryConfig: {
            /** Connector Ids */
            connector_ids?: string[];
            /**
             * Doc Max Tokens
             * @default 2000
             */
            doc_max_tokens: number;
            /**
             * Doc Min Score
             * @default 0.35
             */
            doc_min_score: number;
            /**
             * Doc Top K
             * @default 6
             */
            doc_top_k: number;
            /**
             * Memory Enabled
             * @default true
             */
            memory_enabled: boolean;
            /**
             * Memory Max Tokens
             * @default 600
             */
            memory_max_tokens: number;
            /**
             * Memory Top K
             * @default 8
             */
            memory_top_k: number;
            /**
             * On Retrieval Error
             * @default fail_open
             * @enum {string}
             */
            on_retrieval_error: "fail_open" | "fail_closed";
            /**
             * Query Strategy
             * @default last_user_message
             * @enum {string}
             */
            query_strategy: "last_user_message" | "last_n_turns";
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** ModelCard */
        ModelCard: {
            /** Created */
            created?: number;
            /** Id */
            id: string;
            /**
             * Object
             * @default model
             */
            object: string;
            /**
             * Owned By
             * @default memory-gateway
             */
            owned_by: string;
        };
        /** ModelCreateRequest */
        ModelCreateRequest: {
            /**
             * Auth Type
             * @default bearer
             */
            auth_type: string;
            /** Base Url */
            base_url: string;
            /** Credential */
            credential?: string | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            };
            /** Description */
            description?: string | null;
            /**
             * Dialect
             * @default openai
             */
            dialect: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Extra Headers */
            extra_headers?: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /**
             * Scope
             * @default org
             */
            scope: string;
            /** System Context */
            system_context?: string | null;
            /**
             * Timeout Seconds
             * @default 60
             */
            timeout_seconds: number;
            /** Upstream Model Id */
            upstream_model_id: string;
        };
        /** ModelList */
        ModelList: {
            /** Data */
            data?: components["schemas"]["ModelCard"][];
            /**
             * Object
             * @default list
             */
            object: string;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Auth Type */
            auth_type: string;
            /** Base Url */
            base_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            credential: components["schemas"]["CredentialStatus"];
            /** Default Params */
            default_params: {
                [key: string]: unknown;
            };
            /** Description */
            description: string | null;
            /** Dialect */
            dialect: string;
            /** Editable */
            editable: boolean;
            /** Enabled */
            enabled: boolean;
            /** Extra Headers */
            extra_headers: {
                [key: string]: string;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Organization Id */
            organization_id: string | null;
            /** Scope */
            scope: string;
            /** System Context */
            system_context: string | null;
            /** Timeout Seconds */
            timeout_seconds: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Upstream Model Id */
            upstream_model_id: string;
        };
        /**
         * ModelTestRequest
         * @description An unsaved draft to probe.
         *
         *     The same body as create, so the form can send exactly what it is about to save. It
         *     inherits ``scope`` too, which the probe ignores — a connection does not care who owns
         *     the row it will become.
         */
        ModelTestRequest: {
            /**
             * Auth Type
             * @default bearer
             */
            auth_type: string;
            /** Base Url */
            base_url: string;
            /** Credential */
            credential?: string | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            };
            /** Description */
            description?: string | null;
            /**
             * Dialect
             * @default openai
             */
            dialect: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Extra Headers */
            extra_headers?: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /**
             * Scope
             * @default org
             */
            scope: string;
            /** System Context */
            system_context?: string | null;
            /**
             * Timeout Seconds
             * @default 60
             */
            timeout_seconds: number;
            /** Upstream Model Id */
            upstream_model_id: string;
        };
        /** ModelTrafficResponse */
        ModelTrafficResponse: {
            /** Model Name */
            model_name?: string | null;
            /** Requests */
            requests: number;
            /** Upstream Model Id */
            upstream_model_id?: string | null;
        };
        /**
         * ModelUpdateRequest
         * @description Partial. Only fields actually present in the body are applied.
         */
        ModelUpdateRequest: {
            /** Auth Type */
            auth_type?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Credential */
            credential?: string | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            } | null;
            /** Description */
            description?: string | null;
            /** Dialect */
            dialect?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Extra Headers */
            extra_headers?: {
                [key: string]: string;
            } | null;
            /** Name */
            name?: string | null;
            /** System Context */
            system_context?: string | null;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /** Upstream Model Id */
            upstream_model_id?: string | null;
        };
        /** OrganizationCreateRequest */
        OrganizationCreateRequest: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** OrganizationResponse */
        OrganizationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Gateway Count
             * @default 0
             */
            gateway_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /** Name */
            name: string;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /** OrganizationSummary */
        OrganizationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /** OrganizationUpdateRequest */
        OrganizationUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
            /** Slug */
            slug?: string | null;
            /** Status */
            status?: string | null;
        };
        /** Page[GatewayResponse] */
        Page_GatewayResponse_: {
            /** Items */
            items: components["schemas"]["GatewayResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[InvitationResponse] */
        Page_InvitationResponse_: {
            /** Items */
            items: components["schemas"]["InvitationResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[MemberResponse] */
        Page_MemberResponse_: {
            /** Items */
            items: components["schemas"]["MemberResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[ModelResponse] */
        Page_ModelResponse_: {
            /** Items */
            items: components["schemas"]["ModelResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[OrganizationResponse] */
        Page_OrganizationResponse_: {
            /** Items */
            items: components["schemas"]["OrganizationResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[RequestLogResponse] */
        Page_RequestLogResponse_: {
            /** Items */
            items: components["schemas"]["RequestLogResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PasswordChangeRequest */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PercentilesResponse */
        PercentilesResponse: {
            /** P50 */
            p50?: number | null;
            /** P95 */
            p95?: number | null;
            /** P99 */
            p99?: number | null;
        };
        /**
         * ProbeResponse
         * @description The four things the button reports. Not an error envelope: "the upstream said 401"
         *     is the successful answer to "does this work", and the UI renders it in red itself.
         */
        ProbeResponse: {
            /** Error Message */
            error_message?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model Echo */
            model_echo?: string | null;
            /** Ok */
            ok: boolean;
            /** Upstream Status */
            upstream_status?: number | null;
        };
        /** PromptMessageResponse */
        PromptMessageResponse: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /**
         * RequestDetailResponse
         * @description One request, with everything the §10.3 drawer draws.
         *
         *     ``routing`` and the retrieval lists are here and empty until tasks 08 and 10 fill
         *     them, for the same reason the gateway editor shows its unbuilt sections: a drawer
         *     that grows two panels later moves everything the reader has learned the position of.
         */
        RequestDetailResponse: {
            /** Failover Attempts */
            failover_attempts: unknown[];
            log: components["schemas"]["RequestLogResponse"];
            /** Retrieved Chunk Ids */
            retrieved_chunk_ids: unknown[];
            /** Retrieved Fact Ids */
            retrieved_fact_ids: unknown[];
            transcript?: components["schemas"]["TranscriptResponse"] | null;
        };
        /**
         * RequestLogResponse
         * @description One row of the request table. No bodies — that is what the detail view is for.
         */
        RequestLogResponse: {
            /** Api Key Id */
            api_key_id: string | null;
            /** Bodies Omitted */
            bodies_omitted: string | null;
            /** Completion Tokens */
            completion_tokens: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** End User Id */
            end_user_id: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Gateway Id
             * Format: uuid
             */
            gateway_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latency Retrieval Ms */
            latency_retrieval_ms: number | null;
            /** Latency Total Ms */
            latency_total_ms: number;
            /** Latency Ttft Ms */
            latency_ttft_ms: number | null;
            /** Latency Upstream Ms */
            latency_upstream_ms: number | null;
            /** Memory Tokens */
            memory_tokens: number | null;
            /** Model Name */
            model_name: string | null;
            /** Prompt Tokens */
            prompt_tokens: number | null;
            /** Request Id */
            request_id: string | null;
            /** Response Truncated */
            response_truncated: boolean;
            /** Session Id */
            session_id: string | null;
            /** Status Code */
            status_code: number;
            /** Streamed */
            streamed: boolean;
            /** Upstream Model Id */
            upstream_model_id: string | null;
        };
        /** SeriesResponse */
        SeriesResponse: {
            /** Buckets */
            buckets: components["schemas"]["BucketResponse"][];
            /** Interval Seconds */
            interval_seconds: number;
        };
        /**
         * SessionResponse
         * @description What login and refresh both return.
         *
         *     The refresh token is deliberately absent: it lives in an httpOnly cookie the
         *     JavaScript never sees, which is the whole point of splitting the two.
         */
        SessionResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserSummary"];
        };
        /**
         * SummaryResponse
         * @description The cards, the latency numbers, and the two distribution charts.
         */
        SummaryResponse: {
            /** Completion Tokens */
            completion_tokens: number;
            /** Error Groups */
            error_groups: components["schemas"]["ErrorGroupResponse"][];
            /** Error Rate */
            error_rate: number;
            /** Errors */
            errors: number;
            /** Memory Tokens */
            memory_tokens: number;
            /** Models */
            models: components["schemas"]["ModelTrafficResponse"][];
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Requests */
            requests: number;
            retrieval: components["schemas"]["PercentilesResponse"];
            /** Status Classes */
            status_classes: {
                [key: string]: number;
            };
            total: components["schemas"]["PercentilesResponse"];
            ttft: components["schemas"]["PercentilesResponse"];
        };
        /**
         * TargetSummary
         * @description The model a gateway routes to, as much of it as a gateway screen needs.
         *
         *     Deliberately not the full ``ModelResponse``: nothing here can carry a credential
         *     status, so the gateway editor cannot become a second place a hint is rendered.
         */
        TargetSummary: {
            /** Dialect */
            dialect: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Organization Id */
            organization_id: string | null;
        };
        /**
         * TranscriptResponse
         * @description The bodies, as far as they were stored.
         */
        TranscriptResponse: {
            /** Assembled Prompt */
            assembled_prompt?: {
                [key: string]: unknown;
            }[] | null;
            /** Distilled At */
            distilled_at?: string | null;
            /** Request Body */
            request_body?: {
                [key: string]: unknown;
            }[] | null;
            /** Response Body */
            response_body?: string | null;
        };
        /** UserSummary */
        UserSummary: {
            /** Capabilities */
            capabilities?: string[];
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Login At */
            last_login_at?: string | null;
            /** Name */
            name: string;
            organization?: components["schemas"]["OrganizationSummary"] | null;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
        };
    };
    change_password_api_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    list_gateways_api_v1_gateways_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GatewayResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_gateway_api_v1_gateways_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gateway_api_v1_gateways__gateway_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gateway_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_gateway_api_v1_gateways__gateway_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gateway_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_gateway_api_v1_gateways__gateway_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gateway_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_api_v1_gateways__gateway_id__keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gateway_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_key_api_v1_gateways__gateway_id__keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gateway_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedApiKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_gateway_api_v1_gateways__gateway_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gateway_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invitations_api_v1_invitations_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InvitationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_invitation_api_v1_invitations_accept__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invitation_api_v1_invitations_accept__token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_api_v1_invitations__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_invitation_api_v1_invitations__invitation_id__resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedInvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key_api_v1_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_logs_api_v1_logs_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                gateway_id?: string | null;
                upstream_model_id?: string | null;
                status_class?: string | null;
                end_user_id?: string | null;
                session_id?: string | null;
                streamed?: boolean | null;
                min_latency_ms?: number | null;
                search?: string | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RequestLogResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_log_api_v1_logs__log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_v1_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_summary_api_v1_metrics_summary_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                gateway_id?: string | null;
                upstream_model_id?: string | null;
                status_class?: string | null;
                end_user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_timeseries_api_v1_metrics_timeseries_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                metric?: string;
                group_by?: string;
                interval?: number | null;
                gateway_id?: string | null;
                upstream_model_id?: string | null;
                status_class?: string | null;
                end_user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: {
                scope?: string | null;
                enabled?: boolean | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ModelResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_model_api_v1_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_draft_api_v1_models_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_v1_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_api_v1_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_api_v1_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_api_v1_models__model_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organizations_api_v1_organizations_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrganizationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_api_v1_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_api_v1_organizations__organization_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_organization_api_v1_organizations__organization_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_api_v1_organizations__organization_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedInvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_organizations__organization_id__members_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MemberResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_completions_g__slug__v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_g__slug__v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
