/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the session family and clear the cookie.
         *
         *     Unauthenticated and idempotent on purpose: a user whose access token has already
         *     expired must still be able to end their session, and a logout that returns 401 leaves
         *     the browser holding a live refresh cookie.
         *
         *     Returns ``None`` rather than a ``Response``: FastAPI merges the injected response's
         *     headers only on that path, and returning one directly would drop the Set-Cookie.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change your own password and sign every *other* session out.
         *
         *     Other sessions keep working for up to one access-token TTL: their refresh tokens are
         *     dead immediately, but an access token already issued is self-contained. Fifteen
         *     minutes is the documented cost of not doing a token lookup on the data plane; if that
         *     is ever unacceptable, the fix is a revocation list, not a shorter TTL.
         */
        post: operations["change_password_api_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange the refresh cookie for a new access token and a new refresh token.
         *
         *     Deliberately unauthenticated: by the time a client calls this, its access token has
         *     expired, which is the only reason it is calling.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invitations
         * @description No ``accept_url`` here, and there cannot be one: only the hash is stored. Use
         *     resend to mint a fresh link.
         */
        get: operations["list_invitations_api_v1_invitations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Invitation
         * @description Validate a link so the page can render before anyone types a password.
         *
         *     Answers 404 for unknown, expired and already-accepted alike: the token is a bearer
         *     credential, and a caller holding the wrong one learns nothing about which it was.
         */
        get: operations["preview_invitation_api_v1_invitations_accept__token__get"];
        put?: never;
        /**
         * Accept Invitation
         * @description Create the account and sign it in.
         *
         *     Two transactions, not one: the directory creates the user and burns the invitation,
         *     then auth opens a session. If the second half fails the account still exists and the
         *     person can sign in normally, which is a better failure than a consumed invitation and
         *     no account.
         */
        post: operations["accept_invitation_api_v1_invitations_accept__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invitation */
        delete: operations["revoke_invitation_api_v1_invitations__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{invitation_id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Invitation
         * @description Mints a new link and invalidates the previous one.
         */
        post: operations["resend_invitation_api_v1_invitations__invitation_id__resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_members__member_id__delete"];
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_api_v1_members__member_id__patch"];
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description The caller's own models plus the global catalog, newest first.
         *
         *     One endpoint for both tabs: ``?scope=global`` and ``?scope=org`` are a filter over the
         *     same list rather than two shapes, so the client pages them identically and a model
         *     cannot appear in one view and not the other.
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        /** Create Model */
        post: operations["create_model_api_v1_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Draft
         * @description Probe a configuration that has not been saved.
         *
         *     Declared before ``/models/{model_id}`` so ``test`` is not swallowed as an id — FastAPI
         *     matches in declaration order, and ``uuid.UUID`` would reject it with a 422 that reads
         *     like the endpoint is broken.
         */
        post: operations["test_draft_api_v1_models_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_api_v1_models__model_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Model
         * @description 409 with the referencing gateways named if one points at this model.
         */
        delete: operations["delete_model_api_v1_models__model_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Model
         * @description Partial. An omitted ``credential`` keeps the stored one; an explicit ``null``
         *     clears it. There is no way to read it back, so rotation is replacement.
         */
        patch: operations["update_model_api_v1_models__model_id__patch"];
        trace?: never;
    };
    "/api/v1/models/{model_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Model
         * @description Send a one-token completion using the model exactly as stored.
         *
         *     Nothing about the request can be overridden here. A caller who could aim a *stored*
         *     credential at a URL of their choosing would have a reveal endpoint in all but name.
         */
        post: operations["test_model_api_v1_models__model_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Organizations
         * @description Every organization for a platform admin; the caller's own, alone, for anyone else.
         *
         *     Not gated on ``platform:administer``: an org user needs this to render their own
         *     organization, and the scope already reduces the answer to one row. A second endpoint
         *     shape for the same information is how the two drift apart.
         */
        get: operations["list_organizations_api_v1_organizations_get"];
        put?: never;
        /** Create Organization */
        post: operations["create_organization_api_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization_api_v1_organizations__organization_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Organization
         * @description Name, slug and defaults for an org admin; ``status`` for a platform admin only.
         *
         *     Refused rather than ignored: an organization that could suspend itself could also
         *     un-suspend itself, which would make suspension advisory.
         */
        patch: operations["update_organization_api_v1_organizations__organization_id__patch"];
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invitation
         * @description Creates the invitation and returns the link — the only time it exists.
         *
         *     There is no email delivery in v1 (task 04, out of scope), so the admin copies the URL
         *     and sends it however they already talk to the person.
         */
        post: operations["create_invitation_api_v1_organizations__organization_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Members
         * @description Readable by every role. Seeing who your colleagues are is not an admin power;
         *     changing them is, and that lives on the two routes below.
         */
        get: operations["list_members_api_v1_organizations__organization_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/g/{slug}/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Completions
         * @description Forward a chat completion, streaming or not.
         */
        post: operations["chat_completions_g__slug__v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/g/{slug}/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description The virtual models this gateway exposes, in OpenAI list format.
         */
        get: operations["list_models_g__slug__v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CredentialStatus
         * @description SPEC §5.4: what a response may say about a stored secret, and no more.
         *
         *     ``hint`` can be ``None`` while ``configured`` is ``True`` — for a row written before
         *     hints were stored, and for a global model being read by someone who does not own it.
         */
        CredentialStatus: {
            /** Configured */
            configured: boolean;
            /** Hint */
            hint?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvitationAcceptRequest */
        InvitationAcceptRequest: {
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** InvitationCreateRequest */
        InvitationCreateRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Role */
            role: string;
        };
        /**
         * InvitationPreviewResponse
         * @description What an unauthenticated visitor may see about a link they hold.
         *
         *     The organization's *name* is here because the page has to say which organization is
         *     being joined; nothing else about it is, and there is no id.
         */
        InvitationPreviewResponse: {
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Organization Name */
            organization_name: string;
            /** Role */
            role: string;
        };
        /** InvitationResponse */
        InvitationResponse: {
            /** Accepted At */
            accepted_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /**
         * IssuedInvitationResponse
         * @description The one response that carries the link.
         *
         *     Only the hash is stored, so this is the single moment it can be shown; the list
         *     endpoint has no ``accept_url`` field to leak later.
         */
        IssuedInvitationResponse: {
            /** Accept Url */
            accept_url: string;
            invitation: components["schemas"]["InvitationResponse"];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember
             * @default false
             */
            remember: boolean;
        };
        /** MemberResponse */
        MemberResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Login At */
            last_login_at?: string | null;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** MemberUpdateRequest */
        MemberUpdateRequest: {
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
        };
        /** ModelCard */
        ModelCard: {
            /** Created */
            created?: number;
            /** Id */
            id: string;
            /**
             * Object
             * @default model
             */
            object: string;
            /**
             * Owned By
             * @default memory-gateway
             */
            owned_by: string;
        };
        /** ModelCreateRequest */
        ModelCreateRequest: {
            /**
             * Auth Type
             * @default bearer
             */
            auth_type: string;
            /** Base Url */
            base_url: string;
            /** Credential */
            credential?: string | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            };
            /** Description */
            description?: string | null;
            /**
             * Dialect
             * @default openai
             */
            dialect: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Extra Headers */
            extra_headers?: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /**
             * Scope
             * @default org
             */
            scope: string;
            /** System Context */
            system_context?: string | null;
            /**
             * Timeout Seconds
             * @default 60
             */
            timeout_seconds: number;
            /** Upstream Model Id */
            upstream_model_id: string;
        };
        /** ModelList */
        ModelList: {
            /** Data */
            data?: components["schemas"]["ModelCard"][];
            /**
             * Object
             * @default list
             */
            object: string;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Auth Type */
            auth_type: string;
            /** Base Url */
            base_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            credential: components["schemas"]["CredentialStatus"];
            /** Default Params */
            default_params: {
                [key: string]: unknown;
            };
            /** Description */
            description: string | null;
            /** Dialect */
            dialect: string;
            /** Editable */
            editable: boolean;
            /** Enabled */
            enabled: boolean;
            /** Extra Headers */
            extra_headers: {
                [key: string]: string;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Organization Id */
            organization_id: string | null;
            /** Scope */
            scope: string;
            /** System Context */
            system_context: string | null;
            /** Timeout Seconds */
            timeout_seconds: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Upstream Model Id */
            upstream_model_id: string;
        };
        /**
         * ModelTestRequest
         * @description An unsaved draft to probe.
         *
         *     The same body as create, so the form can send exactly what it is about to save. It
         *     inherits ``scope`` too, which the probe ignores — a connection does not care who owns
         *     the row it will become.
         */
        ModelTestRequest: {
            /**
             * Auth Type
             * @default bearer
             */
            auth_type: string;
            /** Base Url */
            base_url: string;
            /** Credential */
            credential?: string | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            };
            /** Description */
            description?: string | null;
            /**
             * Dialect
             * @default openai
             */
            dialect: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Extra Headers */
            extra_headers?: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /**
             * Scope
             * @default org
             */
            scope: string;
            /** System Context */
            system_context?: string | null;
            /**
             * Timeout Seconds
             * @default 60
             */
            timeout_seconds: number;
            /** Upstream Model Id */
            upstream_model_id: string;
        };
        /**
         * ModelUpdateRequest
         * @description Partial. Only fields actually present in the body are applied.
         */
        ModelUpdateRequest: {
            /** Auth Type */
            auth_type?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Credential */
            credential?: string | null;
            /** Default Params */
            default_params?: {
                [key: string]: unknown;
            } | null;
            /** Description */
            description?: string | null;
            /** Dialect */
            dialect?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Extra Headers */
            extra_headers?: {
                [key: string]: string;
            } | null;
            /** Name */
            name?: string | null;
            /** System Context */
            system_context?: string | null;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /** Upstream Model Id */
            upstream_model_id?: string | null;
        };
        /** OrganizationCreateRequest */
        OrganizationCreateRequest: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** OrganizationResponse */
        OrganizationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Gateway Count
             * @default 0
             */
            gateway_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /** Name */
            name: string;
            /** Settings */
            settings: {
                [key: string]: unknown;
            };
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /** OrganizationSummary */
        OrganizationSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /** OrganizationUpdateRequest */
        OrganizationUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
            /** Slug */
            slug?: string | null;
            /** Status */
            status?: string | null;
        };
        /** Page[InvitationResponse] */
        Page_InvitationResponse_: {
            /** Items */
            items: components["schemas"]["InvitationResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[MemberResponse] */
        Page_MemberResponse_: {
            /** Items */
            items: components["schemas"]["MemberResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[ModelResponse] */
        Page_ModelResponse_: {
            /** Items */
            items: components["schemas"]["ModelResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[OrganizationResponse] */
        Page_OrganizationResponse_: {
            /** Items */
            items: components["schemas"]["OrganizationResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PasswordChangeRequest */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ProbeResponse
         * @description The four things the button reports. Not an error envelope: "the upstream said 401"
         *     is the successful answer to "does this work", and the UI renders it in red itself.
         */
        ProbeResponse: {
            /** Error Message */
            error_message?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model Echo */
            model_echo?: string | null;
            /** Ok */
            ok: boolean;
            /** Upstream Status */
            upstream_status?: number | null;
        };
        /**
         * SessionResponse
         * @description What login and refresh both return.
         *
         *     The refresh token is deliberately absent: it lives in an httpOnly cookie the
         *     JavaScript never sees, which is the whole point of splitting the two.
         */
        SessionResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserSummary"];
        };
        /** UserSummary */
        UserSummary: {
            /** Capabilities */
            capabilities?: string[];
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Login At */
            last_login_at?: string | null;
            /** Name */
            name: string;
            organization?: components["schemas"]["OrganizationSummary"] | null;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
        };
    };
    change_password_api_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    list_invitations_api_v1_invitations_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InvitationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_invitation_api_v1_invitations_accept__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invitation_api_v1_invitations_accept__token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_api_v1_invitations__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_invitation_api_v1_invitations__invitation_id__resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedInvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_v1_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: {
                scope?: string | null;
                enabled?: boolean | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ModelResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_model_api_v1_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_draft_api_v1_models_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_v1_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_api_v1_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_api_v1_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_api_v1_models__model_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organizations_api_v1_organizations_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OrganizationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_api_v1_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_api_v1_organizations__organization_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_organization_api_v1_organizations__organization_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_api_v1_organizations__organization_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedInvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_organizations__organization_id__members_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MemberResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_completions_g__slug__v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_g__slug__v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
