/**
 * The server's types, not a hand-written copy of them.
 *
 * `schema.d.ts` is generated from the FastAPI schema by `make openapi`, and CI fails if
 * the checked-in copy has drifted. Aliasing the pieces the app uses here is what makes
 * that check bite: rename a field on the server and this file stops compiling, instead
 * of the UI quietly rendering `undefined`.
 */

import type { components } from '@/api/schema'

export type SessionResponse = components['schemas']['SessionResponse']
export type CurrentUser = components['schemas']['UserSummary']
export type OrganizationSummary = components['schemas']['OrganizationSummary']
export type LoginRequest = components['schemas']['LoginRequest']
export type PasswordChangeRequest = components['schemas']['PasswordChangeRequest']

export type OrganizationResponse = components['schemas']['OrganizationResponse']
export type OrganizationCreateRequest = components['schemas']['OrganizationCreateRequest']
export type OrganizationUpdateRequest = components['schemas']['OrganizationUpdateRequest']
export type MemberResponse = components['schemas']['MemberResponse']
export type MemberUpdateRequest = components['schemas']['MemberUpdateRequest']
export type InvitationResponse = components['schemas']['InvitationResponse']
export type InvitationCreateRequest = components['schemas']['InvitationCreateRequest']
export type IssuedInvitationResponse = components['schemas']['IssuedInvitationResponse']
export type InvitationPreviewResponse = components['schemas']['InvitationPreviewResponse']
export type InvitationAcceptRequest = components['schemas']['InvitationAcceptRequest']

export type ModelResponse = components['schemas']['ModelResponse']
export type ModelCreateRequest = components['schemas']['ModelCreateRequest']
export type ModelUpdateRequest = components['schemas']['ModelUpdateRequest']
export type ModelTestRequest = components['schemas']['ModelTestRequest']
export type CredentialStatus = components['schemas']['CredentialStatus']
export type ProbeResponse = components['schemas']['ProbeResponse']
export type TokenizerSpec = components['schemas']['TokenizerSpec']
export type EffectiveTokenizerResponse = components['schemas']['EffectiveTokenizerResponse']
export type CalibrationResponse = components['schemas']['CalibrationResponse']
export type TokenizersResponse = components['schemas']['TokenizersResponse']
export type DerivationResponse = components['schemas']['DerivationResponse']

export type GatewayResponse = components['schemas']['GatewayResponse']
export type GatewayCreateRequest = components['schemas']['GatewayCreateRequest']
export type GatewayUpdateRequest = components['schemas']['GatewayUpdateRequest']
export type GatewayTestRequest = components['schemas']['GatewayTestRequest']
export type GatewayTestResponse = components['schemas']['GatewayTestResponse']
export type TargetSummary = components['schemas']['TargetSummary']
export type GatewayTargetRequest = components['schemas']['GatewayTargetRequest']
export type AttemptResponse = components['schemas']['AttemptResponse']
export type MemoryConfig = components['schemas']['MemoryConfig']
export type MemoryPreviewRequest = components['schemas']['MemoryPreviewRequest']
export type RetrievalPreviewResponse = components['schemas']['RetrievalPreviewResponse']
export type RetrievedChunkResponse = components['schemas']['RetrievedChunkResponse']
export type PromptPreviewResponse = components['schemas']['PromptPreviewResponse']
export type PromptLayerResponse = components['schemas']['PromptLayerResponse']
export type LoggingConfig = components['schemas']['LoggingConfig']
export type LimitsConfig = components['schemas']['LimitsConfig']
export type ApiKeyResponse = components['schemas']['ApiKeyResponse']
export type ApiKeyCreateRequest = components['schemas']['ApiKeyCreateRequest']
export type IssuedApiKeyResponse = components['schemas']['IssuedApiKeyResponse']

export type ConnectorResponse = components['schemas']['ConnectorResponse']
export type ConnectorCreateRequest = components['schemas']['ConnectorCreateRequest']
export type ConnectorUpdateRequest = components['schemas']['ConnectorUpdateRequest']
export type ChunkingConfig = components['schemas']['ChunkingConfig']
export type DocumentResponse = components['schemas']['DocumentResponse']
export type UploadResponse = components['schemas']['UploadResponse']
export type UploadOutcomeResponse = components['schemas']['UploadOutcomeResponse']
export type UploadUrlResponse = components['schemas']['UploadUrlResponse']
export type ResyncResponse = components['schemas']['ResyncResponse']
export type SearchRequest = components['schemas']['SearchRequest']
export type SearchResponse = components['schemas']['SearchResponse']
export type SearchHit = components['schemas']['SearchHit']
export type DocumentChunk = components['schemas']['DocumentChunk']
export type DocumentChunksResponse = components['schemas']['DocumentChunksResponse']
export type ChunkingPreviewResponse = components['schemas']['ChunkingPreviewResponse']
export type ChunkingCandidate = components['schemas']['ChunkingCandidateResponse']
export type PreviewChunk = components['schemas']['PreviewChunkResponse']
export type SummarizationConfig = components['schemas']['SummarizationConfig']
export type SummarizationOverride = components['schemas']['SummarizationOverride']
export type SummaryModelResponse = components['schemas']['SummaryModelResponse']
export type SummarizationCostResponse = components['schemas']['SummarizationCostResponse']
export type SummaryEditRequest = components['schemas']['SummaryEditRequest']
export type SummarizationSettings = components['schemas']['SummarizationSettingsResponse']
export type SummarizationSettingsRequest = components['schemas']['SummarizationSettingsRequest']
export type SummarizationHealth = components['schemas']['SummarizationHealthResponse']
export type SummarizationDay = components['schemas']['SummarizationDayResponse']

export type EndUserResponse = components['schemas']['EndUserResponse']
export type MemoryFactResponse = components['schemas']['MemoryFactResponse']
export type MemoryFactCreateRequest = components['schemas']['MemoryFactCreateRequest']
export type MemoryFactUpdateRequest = components['schemas']['MemoryFactUpdateRequest']
export type MemorySearchResponse = components['schemas']['MemorySearchResponse']
export type MemorySearchHit = components['schemas']['MemorySearchHit']
export type MemoryPurgeResponse = components['schemas']['MemoryPurgeResponse']

export type DistillationConfig = components['schemas']['DistillationConfig']
export type DistillationUsage = components['schemas']['DistillationUsage']
export type DistillationSettings = components['schemas']['DistillationSettingsResponse']
export type DistillationSettingsRequest = components['schemas']['DistillationSettingsRequest']
export type MemoryHealth = components['schemas']['MemoryHealthResponse']
export type MemoryHealthDay = components['schemas']['MemoryHealthDayResponse']
export type ManualPassResponse = components['schemas']['ManualPassResponse']

export type SummaryResponse = components['schemas']['SummaryResponse']
export type SeriesResponse = components['schemas']['SeriesResponse']
export type BucketResponse = components['schemas']['BucketResponse']
export type PercentilesResponse = components['schemas']['PercentilesResponse']
export type ModelTrafficResponse = components['schemas']['ModelTrafficResponse']
export type ErrorGroupResponse = components['schemas']['ErrorGroupResponse']
export type RequestLogResponse = components['schemas']['RequestLogResponse']
export type RequestDetailResponse = components['schemas']['RequestDetailResponse']
export type TranscriptResponse = components['schemas']['TranscriptResponse']

export type GatewayLimits = components['schemas']['GatewayLimitsResponse']
export type LimitQuota = components['schemas']['QuotaResponse']
export type LimitUsage = components['schemas']['LimitUsageResponse']
export type LimitPressure = components['schemas']['PressureResponse']
export type LimitPressureList = components['schemas']['PressureListResponse']
export type ThrottledEndUser = components['schemas']['ThrottledEndUserResponse']
export type ThrottledEndUsers = components['schemas']['ThrottledEndUsersResponse']

export type AuditEvent = components['schemas']['AuditEventResponse']
export type AuditChange = components['schemas']['AuditChangeResponse']

export type OrganizationPage = components['schemas']['Page_OrganizationResponse_']
export type MemberPage = components['schemas']['Page_MemberResponse_']
export type InvitationPage = components['schemas']['Page_InvitationResponse_']
export type ModelPage = components['schemas']['Page_ModelResponse_']
export type GatewayPage = components['schemas']['Page_GatewayResponse_']
export type ConnectorPage = components['schemas']['Page_ConnectorResponse_']
export type DocumentPage = components['schemas']['Page_DocumentResponse_']
export type RequestLogPage = components['schemas']['Page_RequestLogResponse_']
export type EndUserPage = components['schemas']['Page_EndUserResponse_']
export type MemoryFactPage = components['schemas']['Page_MemoryFactResponse_']
export type AuditEventPage = components['schemas']['Page_AuditEventResponse_']

export type PlatformSettings = components['schemas']['PlatformSettings']
export type PlatformSettingsResponse = components['schemas']['PlatformSettingsResponse']
export type PlatformSettingsPatch = components['schemas']['PlatformSettingsPatch']
export type EmbeddingChoice = components['schemas']['EmbeddingChoice']
export type RetentionCeilings = components['schemas']['RetentionCeilings']
export type StorageCaps = components['schemas']['StorageCaps']
export type LimitPolicy = components['schemas']['LimitPolicy']
export type SettingAttribution = components['schemas']['SettingAttribution']
export type MaintenanceResponse = components['schemas']['MaintenanceResponse']
export type MaintenanceRun = components['schemas']['MaintenanceRunResponse']
export type PartitionRunway = components['schemas']['PartitionRunway']
export type ReindexRun = components['schemas']['ReindexRunResponse']
export type ReindexTarget = components['schemas']['ReindexTargetResponse']
export type ReindexEstimate = components['schemas']['ReindexEstimate']
export type SweepResponse = components['schemas']['SweepResponse']
export type OrphanGroup = components['schemas']['OrphanGroup']
export type ErasureReport = components['schemas']['ErasureReport']
export type OrganizationDeletionRequest = components['schemas']['OrganizationDeletionRequest']
export type RetentionCeilingsResponse = components['schemas']['RetentionCeilingsResponse']

// Task 103: validation — index audits and retrieval evaluation.
export type AuditStatusResponse = components['schemas']['AuditStatusResponse']
export type AuditResponse = components['schemas']['AuditResponse']
export type AuditRequest = components['schemas']['AuditRequest']
export type AuditAlertResponse = components['schemas']['AuditAlertResponse']
export type ChunkingReportResponse = components['schemas']['ChunkingReportResponse']
export type EmbeddingReportResponse = components['schemas']['EmbeddingReportResponse']
export type FindingResponse = components['schemas']['FindingResponse']
export type HistogramResponse = components['schemas']['HistogramResponse']
export type DistributionResponse = components['schemas']['DistributionResponse']
export type EvaluationSetResponse = components['schemas']['EvaluationSetResponse']
export type EvaluationSetDetailResponse = components['schemas']['EvaluationSetDetailResponse']
export type EvaluationSetRequest = components['schemas']['EvaluationSetRequest']
export type EvaluationSetPatch = components['schemas']['EvaluationSetPatch']
export type EvaluationItemResponse = components['schemas']['EvaluationItemResponse']
export type EvaluationItemRequest = components['schemas']['EvaluationItemRequest']
export type EvaluationItemPatch = components['schemas']['EvaluationItemPatch']
export type EvaluationRunSummaryResponse = components['schemas']['EvaluationRunSummaryResponse']
export type EvaluationRunResponse = components['schemas']['EvaluationRunResponse']
export type RunRequest = components['schemas']['RunRequest']
export type RunDiffResponse = components['schemas']['RunDiffResponse']
export type ImportRequest = components['schemas']['ImportRequest']
export type ImportResponse = components['schemas']['ImportResponse']
export type GenerateRequest = components['schemas']['GenerateRequest']
export type GenerateResponse = components['schemas']['GenerateResponse']

// Task 104: reprocessing status — the second status axis, the runs, and the alerts.
export type ReprocessingRunResponse = components['schemas']['ReprocessingRunResponse']
export type ReprocessingProgress = components['schemas']['ReprocessingProgress']
export type ReprocessRequest = components['schemas']['ReprocessRequest']
export type StalePreviewResponse = components['schemas']['StalePreviewResponse']
export type StaleAlertResponse = components['schemas']['StaleAlertResponse']
export type StaleConnectorResponse = components['schemas']['StaleConnectorResponse']
