"""Request logs and transcripts, partitioned by day.

Hand-written rather than autogenerated, because Alembic cannot express ``PARTITION BY``
and would produce two ordinary tables that work perfectly until the first retention run
has to delete a hundred million rows from underneath a live proxy.

Three decisions are baked into the DDL below.

**Daily range partitions on ``created_at``.** Retention (task 17) becomes ``DROP TABLE``
on a partition, which takes a brief exclusive lock on one day's data and returns the disk
immediately. The alternative — ``DELETE ... WHERE created_at < now() - interval``  — holds
a long transaction, bloats the table, and competes with the write path for exactly as long
as it runs.

**A ``_default`` partition.** Thirty days of runway is created here and task 17 keeps it
rolling, but a deploy that stops running its jobs must not start rejecting inserts: an
insert with no matching partition is an error, and an error on the logging path is a
dropped request record at best. The default partition catches those rows so they are
merely misfiled rather than lost. Task 17 has to detach it before attaching a partition
that overlaps rows it has accumulated, which is the price of the safety net and is
written down in the task file.

**Indexes are created on the parent.** PostgreSQL propagates them to every existing and
future partition, so a partition created by task 17 is indexed without task 17 knowing
what the indexes are.

Revision ID: 0007_request_logging
Revises: 0006_gateways_keys
Create Date: 2026-09-07
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, date, datetime, timedelta

from alembic import op

revision: str = "0007_request_logging"
down_revision: str | None = "0006_gateways_keys"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Runway. Kept in step with ``app.db.models.request_log.PARTITION_DAYS_AHEAD``; a test
#: asserts they agree, because a shorter runway here would silently send every row to the
#: default partition after the window closed.
DAYS_AHEAD = 30
#: One day behind, so a row written during the migration itself — or by a worker whose
#: clock is a little slow — still lands in a real partition.
DAYS_BEHIND = 1


REQUEST_LOGS = """
CREATE TABLE request_logs (
    id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    organization_id uuid NOT NULL,
    gateway_id uuid NOT NULL,
    api_key_id uuid,
    end_user_id uuid,
    session_id varchar(128),
    upstream_model_id uuid,
    model_name text,
    status_code smallint NOT NULL,
    error_code varchar(64),
    error_message text,
    streamed boolean NOT NULL DEFAULT false,
    latency_total_ms integer NOT NULL DEFAULT 0,
    latency_retrieval_ms integer,
    latency_ttft_ms integer,
    latency_upstream_ms integer,
    prompt_tokens integer,
    completion_tokens integer,
    memory_tokens integer,
    retrieved_chunk_ids jsonb NOT NULL DEFAULT '[]',
    retrieved_fact_ids jsonb NOT NULL DEFAULT '[]',
    failover_attempts jsonb NOT NULL DEFAULT '[]',
    request_id varchar(64),
    response_truncated boolean NOT NULL DEFAULT false,
    bodies_omitted varchar(32),
    CONSTRAINT pk_request_logs PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
"""

TRANSCRIPTS = """
CREATE TABLE transcripts (
    request_log_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    organization_id uuid NOT NULL,
    request_body jsonb,
    assembled_prompt jsonb,
    response_body text,
    distilled_at timestamptz,
    CONSTRAINT pk_transcripts PRIMARY KEY (request_log_id, created_at)
) PARTITION BY RANGE (created_at);
"""

INDEXES = (
    # DESC on every one: the monitoring screens and the cursor pages all read the newest
    # rows first, and an ascending index makes that a backward scan on every query.
    "CREATE INDEX ix_request_logs_gateway_id_created_at"
    " ON request_logs (gateway_id, created_at DESC)",
    "CREATE INDEX ix_request_logs_organization_id_created_at"
    " ON request_logs (organization_id, created_at DESC)",
    "CREATE INDEX ix_request_logs_end_user_id_created_at"
    " ON request_logs (end_user_id, created_at DESC)",
    "CREATE INDEX ix_request_logs_errors"
    " ON request_logs (organization_id, created_at DESC) WHERE status_code >= 400",
    "CREATE INDEX ix_transcripts_organization_id_created_at"
    " ON transcripts (organization_id, created_at DESC)",
    "CREATE INDEX ix_transcripts_pending_distillation"
    " ON transcripts (created_at DESC) WHERE distilled_at IS NULL",
)


def upgrade() -> None:
    op.execute(REQUEST_LOGS)
    op.execute(TRANSCRIPTS)
    for statement in INDEXES:
        op.execute(statement)

    for table in ("request_logs", "transcripts"):
        for day in _window():
            op.execute(_partition(table, day))
        op.execute(f"CREATE TABLE {table}_default PARTITION OF {table} DEFAULT")


def downgrade() -> None:
    # Dropping the parent takes every partition with it, including any that task 17 —
    # or a future deploy — created after this migration ran.
    op.execute("DROP TABLE IF EXISTS transcripts")
    op.execute("DROP TABLE IF EXISTS request_logs")


def _window() -> list[date]:
    """The days to create partitions for, relative to when the migration runs.

    Relative rather than absolute because the runway is about deployment time, not about
    when this file was written: a fresh environment stood up next year needs partitions
    for next year, and a fixed range would put its very first request in the default
    partition.
    """
    start = datetime.now(UTC).date() - timedelta(days=DAYS_BEHIND)
    return [start + timedelta(days=offset) for offset in range(DAYS_BEHIND + DAYS_AHEAD + 1)]


def _partition(table: str, day: date) -> str:
    suffix = day.strftime("%Y%m%d")
    # Bounds are explicit UTC timestamps. A bare date literal is interpreted in the
    # session's TimeZone, so the same DDL would carve the day differently depending on
    # who ran it — and rows near midnight would land either side of the boundary.
    return (
        f"CREATE TABLE {table}_{suffix} PARTITION OF {table} "
        f"FOR VALUES FROM ('{day.isoformat()} 00:00:00+00') "
        f"TO ('{(day + timedelta(days=1)).isoformat()} 00:00:00+00')"
    )
